<?php

// Do not edit this file

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;

// Default theme settings values
function resize_images_in_posts__default_settings_values( $settings = array() ) {
	global $content_width;

	$resize_images_in_posts                 = resize_images_in_posts();
	$settings_id                            = $resize_images_in_posts->settings_id;

	$settings[$settings_id . 'resize_images_in_posts']                     = true;
	$settings[$settings_id . 'how_to_resize_in_posts']                     = 'auto_size';
	$settings[$settings_id . 'custom_size_in_posts']                       = (int) $content_width;
	$settings[$settings_id . 'resize_gifs_in_posts']                       = false;
	
	$settings[$settings_id . 'resize_images_in_text_widgets']              = false;
	$settings[$settings_id . 'how_to_resize_in_text_widgets']              = 'auto_size';
	$settings[$settings_id . 'custom_size_in_text_widgets']                = (int) $content_width;
	$settings[$settings_id . 'resize_gifs_in_text_widgets']                = false;

	return $settings;
}

// Default theme settings functions (that will be used later and we can't call them now)
function resize_images_in_posts__default_settings_functions( $settings = array() ) {
	$resize_images_in_posts                                         = resize_images_in_posts();
	$settings_id                                                    = $resize_images_in_posts->settings_id;
	
	$settings[$settings_id . 'site_info']                           = 'resize_images_in_posts__settings_site_info';

	return $settings;
}